- Client/src/App.tsx
- Client/src/Page/Admin.tsx
> Fix : Admin page

- Client/src/App.tsx
- Client/src/Common/Constant/index.ts
- Client/src/Components/Atoms/Button/index.tsx
- Client/src/Components/Atoms/Button/styles.tsx
Fix : Button 가로,길이 높이에 px 추가 
Fix : Button을 div가 아닌 button을 커스텀화
> Fix : Code Review 이후 내용 수정

- Client/src/Common/Style/index.ts
- Client/src/Components/Atoms/StyledLink/index.tsx
- Client/src/Components/Molecules/BoardPreview/Basic/style.tsx
- Client/src/Components/Molecules/BoardPreview/Image/style.tsx
- Client/src/Components/Molecules/ContentTitle/index.tsx
- Client/src/Components/Molecules/Header/Nav.tsx
- Client/src/Components/Molecules/Header/style.tsx
- Client/src/Components/Organisms/Main/BoardContent/index.tsx
- Client/src/Components/Organisms/Main/BoardContent/style.tsx
> Refactor : 메인 페이지 UI 수정

- Client/src/Components/Molecules/Content/studyProject.tsx
- Client/src/Components/Molecules/Content/styles.tsx
- Client/src/Components/Pages/Project.tsx
- Client/src/Components/Templates/Project/index.tsx
- Client/src/Components/Templates/Project/styles.tsx
- Client/src/Components/Templates/Study/index.tsx
프로젝트 UI생성을 위한 Content 컴포넌트 개발
study와 project의 content가 중복되어, 재사용성을 높였습니다.
추후 Content/studyProject 에서 타입에 따라 데이터를 받아오는 함수를 작성해야 할 거 같습니다.
> [ Feat ] 프로젝트 UI 생성

- Server/src/app.module.ts
- Server/src/reservation/dto/create-reservation.dto.ts
- Server/src/reservation/dto/update-reservation.dto.ts
- Server/src/reservation/entitiy/reservation.entity.ts
- Server/src/reservation/reservation.controller.ts
- Server/src/reservation/reservation.service.ts
[진행 작업]
>엔티티 내용 수정 및 월별 과방 신청 데이터 불러오기 추가
[문제 사항]
[해결 방법]
> [BE] 엔티티 수정 및 월별 데이터 api 추가

- Client/public/dummyData/BaekJoonRanking.json
- Client/public/dummyData/FreeBoardContent.json
- Client/public/dummyData/NoticeBoardContent.json
- Client/public/dummyData/PhotoBoardContent.json
- Client/public/dummyData/ProjectBoardContent.json
- Client/public/dummyData/RoomBoardContent.json
- Client/public/dummyData/StudyBoardContent.json
- Client/public/dummyData/checkLogIn.json
- Client/public/dummyData/manifest.json
- Client/public/dummyData/reservation.json
- Client/public/dummyData/reservation/2022/2.json
- Client/src/API/index.ts
- Client/src/Components/Atoms/ContentImg/styles.tsx
- Client/src/Components/Molecules/Account/RegisterInput.tsx
- Client/src/Components/Molecules/PhotoCard/index.tsx
- Client/src/Components/Organisms/Reserve/ReserveCalendar/Body/index.tsx
- Client/src/Recoil/BoardContent/index.ts
- Client/src/Recoil/Reservation/index.tsx
더미데이터 형식이 맞지 않아서 데이터 형식 수정함,
추가로, 지금 갤러리 페이지 이미지랑
before페이지 이미지랑 겹쳐서 에러나는데 이거 해결해야할듯
> Fix : DummyData

- Server/src/auths/auth.service.ts
- Server/src/commons/dto/response-common.dto.ts
[수행 사항]
ResultSuccessResponse 오류 해결
> [ BE ] ResultSuccessResponse 오류 해결

- Server/src/reservation/dto/create-reservation.dto.ts
- Server/src/reservation/reservation.controller.ts
- Server/src/reservation/reservation.service.ts
> [BE] 과방 신청 api res 수정

- Server/src/reservation/dto/create-reservation.dto.ts
- Server/src/reservation/entitiy/reservation.entity.ts
- Server/src/reservation/reservation.controller.ts
- Server/src/reservation/reservation.service.ts
[진행 사항]
> 과방 신청 status 승인, 거절, 진행중으로 변경할 수 있도록 api 추가.
> [BE] 과방 신청 승인, 거절 api 추가

- Server/src/studies/studies.service.ts
[ 수정 사항 ]
기존 : Study 테이블과 UserStudy 테이블을 join 해서 특정 스터디에 신청한 user의 userIdx를 반환.
수정 : Study 테이블과 UserStudy 테이블, User 테이블을 join 해서 특정 스터디에 신청한 user의 정보까지 반환.
> [ BE ] 특정 스터디 불러오기 API 기능 수정

- Server/src/reservation/entitiy/reservation.entity.ts
- Server/src/reservation/reservation.service.ts
[진행사항]
> reservationStatus enum 타입 삭제
> [BE] enum 타입 삭제

- Server/src/projects/entity/project.entity.ts
- Server/src/projects/projects.service.ts
- Server/src/studies/entity/study.entity.ts
- Server/src/studies/studies.service.ts
- Server/src/users/entities/user.entity.ts
[ 수행 사항 ]
- Study/Project/UserStudy/UserProject 엔티티의 status를 enum에서 string으로 변경.
- 각 엔티티에 생성/수정 날짜 속성 추가.
> [ BE ] 스터디/프로젝트 엔티티 status type 변경 및 그에 따른 api 수정

- Client/src/App.tsx
- Client/src/Components/Templates/Page/styles.tsx
- Client/src/Routes/AdminRoute.tsx
- Client/src/Routes/PrivateRoute.tsx
- Client/src/Routes/PublicRoute.tsx
> Feat : Code Splitting

- Server/src/reservation/reservation.controller.ts
- Server/src/reservation/reservation.service.ts
> [BE] Refactor: api res 수정

- Server/src/projects/entity/project.entity.ts
- Server/src/projects/projects.controller.ts
- Server/src/projects/projects.service.ts
- Server/src/studies/entity/study.entity.ts
- Server/src/studies/studies.controller.ts
- Server/src/studies/studies.service.ts
[ 진행 사항 ]
스터디/프로젝트 생성 승인 API, 그에 따른 엔티티 수정 및 스터디/프로젝트 신청 승인/거부 API명 수정
> [ BE ] 스터디/프로젝트 생성 승인 API

- Client/src/Components/Atoms/Button/styles.tsx
- Client/src/Components/Atoms/ContentImg/styles.tsx
- Client/src/Components/Molecules/Content/styles.tsx
- Client/src/Components/Organisms/Before/Content/index.tsx
- Client/src/Components/Organisms/Before/Content/styles.tsx
- Client/src/Components/Organisms/Before/DoItCarousel/index.tsx
- Client/src/Components/Organisms/Before/DoItCarousel/styles.tsx
- Client/src/Components/Organisms/Before/DoItInfo/styles.tsx
- Client/src/Components/Organisms/Before/EnterDoIt/styles.tsx
- Client/src/Components/Organisms/Before/MainImg/styles.tsx
- Client/src/Components/Templates/Before/index.tsx
[ 진행 작업 ]
> before 페이지 반응형 디자인 추가
> [ FE ] Before Page 반응형 디자인

- Client/src/Components/Organisms/Common/Header/index.tsx
- Client/src/Components/Organisms/Page/Footer/styles.tsx
- Client/src/Components/Templates/Page/styles.tsx
[ 진행 작업 ]
> Page 페이지 반응형 디자인 추가, 로그인 버튼 색 수정
> [ FE ] Page 반응형 디자인

- Client/src/Components/Molecules/Account/LoginInput.tsx
- Client/src/Components/Molecules/Account/styles.tsx
[ 진행 작업 ]
> Login 페이지 반응형 디자인 추가
[ 문제 사항 ]
> placeholder 글씨 크기 조절 못함
> [ FE ] Login Page 반응형 디자인

- Client/src/Common/Style/index.ts
- Client/src/Components/Molecules/Account/RegisterInput/RegisterInput.tsx
- Client/src/Components/Molecules/Account/RegisterInput/styles.tsx
- Client/src/Components/Molecules/Account/common.ts
- Client/src/Components/Molecules/Account/styles.tsx
[ 진행 작업 ]
> Register 페이지 반응형 디자인 추가
> [ FE ] Register Page 반응형 디자인

- Server/package-lock.json
- Server/src/reservation/dto/get-reservation.dto.ts
- Server/src/reservation/reservation.controller.ts
- Server/src/reservation/reservation.service.ts
> [BE] 과방 대여 스웨거 수정

- Server/src/projects/projects.service.ts
- Server/src/studies/studies.service.ts
[ 진행 사항 ]
전체 스터디/프로젝트 조회 API 수정
- 응답으로 관련된 모든 userStudies/userProjects를 빼고 (승인된 유저의 수 + 리더인 유저의 수)를 응답.
> [ BE ] 전체 스터디/프로젝트 조회 API 수정

- Client/src/API/Account/index.ts
- Client/src/API/index.ts
- Client/src/Common/Constant/API.ts
- Client/src/Components/Molecules/Account/util.ts
set-Cookie 를 하려하였으나 Server에서 set-cookie를 통해 response header에 cookie를 실어서 보내준것을 확인하였음.
하지만, 브라우저에 저장이 되지 않았음.
근데 내꺼 local로 프론트 백 실행시켰을때는 모두 정상 작동되었음. 하지만, 영일이형이 프론트 백 실행시키면 또 안됌,,
그냥 storage에 저장하기로하였음 => token check 및 동아리 신청 성공
> Fix : Login Cookie => Storage

- Server/src/users/entities/user.entity.ts
컬럼 길이 제한, phoneNumber 정규표현식 추가
> Fix : 유저 회원가입 엔티티 유효성 검사

- Client/src/Components/Atoms/Button/styles.tsx
- Client/src/Components/Molecules/Account/LoginInput.tsx
- Client/src/Components/Molecules/Account/styles.tsx
[ 진행 작업 ]
> 태블릿 화면에서 Login 컨테이너 사이즈 조절
> [ FE ] Register Page 반응형 디자인 수정

- Client/src/Components/Atoms/Button/styles.tsx
- Client/src/Components/Molecules/Account/RegisterInput/styles.tsx
- Client/src/Components/Molecules/Account/styles.tsx
[ 진행 작업 ]
> Login/Register 버튼 크기 조절, 모바일 화면의 경우 font-size 조절
[ 문제 사항 ]
> Global Style로 지정되어있어 font-size에 접근 불가능
[ 해결 방법 ]
> css 우선순위를 높여 해결함
> [ FE ] Login/Register Page 반응형 디자인 수정

- Server/src/main.ts
> [ BE ] Cors에 두잇 도메인 추가

- Server/package.json
- Server/src/main.ts
[ 진행 사항 ]
- 포트 3000번으로 변경
- start:prod  명령어 수정
> [ BE ] 포트 수정 및 배포 명령어 수정

- Server/ecosystem.config.js
[ 진행 작업 ]
> pm2 설정 파일
[ 문제 사항 ]
[ 해결 사항 ]
> [BE] 배포 설정 변경

- Server/src/users/users.controller.ts
> [BE] cicd 테스트 끝

- Server/src/projects/projects.controller.ts
- Server/src/projects/projects.service.ts
> [BE] 프로젝트 API 권한설정

- Server/src/auths/auth.service.ts
- Server/src/club/dto/get-clubUser.dto.ts
- Server/src/departments/entities/department.entity.ts
- Server/src/users/dto/create-user.dto.ts
- Server/src/users/dto/get-user.dto.ts
- Server/src/users/dto/login-user.dto.ts
- Server/src/users/entities/user.entity.ts
- Server/src/users/users.controller.ts
- Server/src/users/users.module.ts
- Server/src/users/users.service.ts
[department DB변경, userID validation추가]
> [BE] department DB변경, userID validation추가
